### ISSUE TITLE
Implement Linear Search

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Algorithms#1]
## Write a program to implement linear search.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by MSoumen** [comment]
I want to work out this problem.

**Comment by G1Joshi** [comment]
Anyone can work on any issue...
Yes @MSoumen you can do this problem, but make sure that the filename should contain your username.

**Comment by MSoumen** [comment]
ooopppss....  Give some seconds..

**Comment by MSoumen** [comment]
Done. I'm giving the name in the format of  UserName_algorithm_name.extention. Is it Okay?

**Comment by MSoumen** [comment]
See you at 1st OCT .

**Comment by ernesto-ca** [comment]
Can i work in this problem please? I really want it!

**Comment by G1Joshi** [comment]
Yes @MSoumen that's absolutely fine

**Comment by G1Joshi** [comment]
Sure @ernesto-ca you can...

**Comment by PuneethKshetty** [comment]
Can i work on this problem please !!! . Even i really want it .....

**Comment by kritika122000** [comment]
Hey buddy let me work on this!!

**Comment by kashika3101** [comment]
I would also like to work on it I would like to work with C++ or Python. Can you please assign it to me?

**Comment by ASHISHAHUJA1904** [comment]
I am interested in solving this issue.

**Comment by pradumio** [comment]
Hey, @G1Joshi I have contributed with the solution of Linear Search algorithm in CPP. Check PR?

**Comment by G1Joshi** [comment]
Sure, @PuneethKshetty, @kritika122000, @kashika3101, @ASHISHAHUJA1904 you can start working on this issue, when you are done, create a pull request and if your solution is correct than I'll merge them.

**Comment by G1Joshi** [comment]
Thanks @pradumio your PR has been merged successfully 🚀

**Comment by AdeshChoudhar19** [comment]
I would like to work on this.

**Comment by AnirudhPanda** [comment]
#53 Done In JAVA

**Comment by ASHISHAHUJA1904** [comment]
Please merge my PR. #42

**Comment by therohanjaiswal** [comment]
Can I contribute to this?

**Comment by mrjoshi0147** [comment]
I am coding solution in java.

**Comment by kashika3101** [comment]
Please review my PR #104 @G1Joshi associated with the recursive implementation of the Linear Search algorithm

**Comment by HANS-2002** [comment]
@G1Joshi please review my PR #215 and merge if suitable.
