### ISSUE TITLE
Implment Hashing Algorithms.

### ISSUE THREAD

**Issue by jinicode** [C0D1NG/Algorithms#106]
I would love to add solution to this hashing problems.
Please add hacktoberfest and hard label.
Happy Hacking.

**Comment by Priyansi** [comment]
Hi can you assign this to me? I can add the Rabin Karp algorithm?

**Comment by jinicode** [comment]
please can you add labels so  that I can send a PR asap .

**Comment by ShyamPraveenSingh** [comment]
Hi @jinicode @Priyansi,
Sorry to see that no one was able to add the labels. However, both of you can work in this issue and submit your code now.
