### ISSUE TITLE
Implement Merge Sort

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Algorithms#12]
## Write a program to implement merge sort.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by BassCoder2808** [comment]
I would like to work on this issue.

**Comment by hacky1997** [comment]
@G1Joshi I want to work it with python. Please assign me

**Comment by AdeshChoudhar19** [comment]
I would like to work on this.

**Comment by therohanjaiswal** [comment]
Hi @G1Joshi , I would like to work on this.

**Comment by FinalGetsugaa** [comment]
I have raised a PR.Can you please look through it.Thanks
