### ISSUE TITLE
Depth First Search (DFS)

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Algorithms#17]
## Write a program to implement depth first search in graphs.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by dipanshug124** [comment]
Please assign this to me.

**Comment by maxsIT** [comment]
Please, assign it to me

**Comment by AdeshChoudhar19** [comment]
I would like to work on this.

**Comment by Bijay555** [comment]
Can you assign this issue to me?

**Comment by pawki07** [comment]
Hey, I would like to work on this issue. Please assign it to me.
