### ISSUE TITLE
Implement Bubble Sort

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Algorithms#2]
## Write a program to implement bubble sort.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by tauseefmohammed2** [comment]
I would like to work on it. Can I implement it in any language?

**Comment by G1Joshi** [comment]
Any one can work on any issue...
Yes @tauseefmohammed2 you can implement it on any language but make sure that the filename should contain your username.

**Comment by tauseefmohammed2** [comment]
Ok. I will do it in C++. Can you please assign it to me? I will send PR on 1st October

**Comment by MSoumen** [comment]
I'm also want to work on it using Python.

**Comment by G1Joshi** [comment]
Yes @MSoumen and @tauseefmohammed2 you both can work on this issue whenever you want,
This issue is open for all, I'm not going to assign it individually.

**Comment by PuneethKshetty** [comment]
I would also like to work on it . Can i implement it in any prefered language? . If yes then i would like to work with C++  or Python. Can you please assign it to me?

**Comment by kritika122000** [comment]
Hey buddy let me work on this!!

**Comment by kashika3101** [comment]
I would also like to work on it . I would like to work with C++. Can you please assign it to me?

**Comment by ASHISHAHUJA1904** [comment]
Could you please allow me to work on this issue.

**Comment by G1Joshi** [comment]
@PuneethKshetty, @kashika3101, @kritika122000 l, @ASHISHAHUJA1904
All of you can start working on this issue, this issue is open for all and all valid Pull request (correct solution) will be merged.

**Comment by Utkarshn10** [comment]
@G1Joshi is anybody working on this algorithm for java. If no one is working on it then I would like to work on it for java  language.

**Comment by sharmasourab93** [comment]
I will do this in python

**Comment by AdeshChoudhar19** [comment]
i would like to work on this.

**Comment by ayush523** [comment]
Hi,I have worked on this issue.Please check.

**Comment by priyalgupta09** [comment]
hey! can i work on this please assign me.
