### ISSUE TITLE
Greatest Common Divisor (GCD)

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Algorithms#23]
## Write a program to find the greatest common divisor of two numbers.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by BassCoder2808** [comment]
I would like to work on this issue.

**Comment by BassCoder2808** [comment]
Can you specify the folder in which we have to add the above file

**Comment by TheCoderNikhil** [comment]
I want to work on this

**Comment by devmohit-live** [comment]
In which folder do we have to add the code?

**Comment by aansh-01** [comment]
can i do this task in cpp

**Comment by ayush523** [comment]
Hi, I would like to work on this issue.

**Comment by AdeshChoudhar19** [comment]
I would like to work on this.

**Comment by JohnWesleyK** [comment]
Hey there,
I'm sorry for not asking if I can work on this. I did implement a function that calculates GCD with Euclidean Algorithm and created a PR for that. I have just started creating PRs, I would really appreciate your feedback.
Thanks again !!!!

**Comment by gudianirudha** [comment]
**I have implemented it using python
Kindly check the code**

**Comment by ernesto-ca** [comment]
I would love to contribute and in the process practice math hahaha🤣
