### ISSUE TITLE
Implement Binary Search

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Algorithms#8]
## Write a program to implement binary search.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by Abhicoder03** [comment]
Hey, I want to work on this.

**Comment by AdeshChoudhar19** [comment]
I would like to work on this.

**Comment by mrjoshi0147** [comment]
Can I code this in Java?

**Comment by yashgupta18** [comment]
Is it still open?

**Comment by AdeshChoudhar19** [comment]
Just make a PR.

**Comment by LaxmiNyamagoud** [comment]
can I work on this issue?

**Comment by LaxmiNyamagoud** [comment]
can you label it as hacktoberfest-accepted
