### ISSUE TITLE
Implement Insertion Sort

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Algorithms#9]
## Write a program to implement insertion sort.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by BassCoder2808** [comment]
I would like to work on this issue.

**Comment by AdeshChoudhar19** [comment]
I would like to work on this.

**Comment by einhawking** [comment]
I would like to work on this.
